config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'contacts#index'
  resources :contacts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/application_record.rb
# frozen_string_literal: true

# The ApplicationRecord class is the base class for all models in the Rails application.
# It provides common functionality and configuration for interacting with the database.
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def self.ransackable_attributes(_auth_object = nil)
    []
  end

  def self.ransackable_associations(_auth_object = nil)
    []
  end
end

app/models/contact.rb
# frozen_string_literal: true

# The Contact class represents a contact entity in the Rails application.
# It encapsulates attributes and behavior related to a contact.
class Contact < ApplicationRecord
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :phone, presence: true

  after_create_commit -> { broadcast_prepend_later_to 'contacts' }
  after_update_commit -> { broadcast_replace_later_to 'contacts' }
  after_destroy_commit -> { broadcast_remove_to 'contacts' }

  paginates_per 10

  def self.ransackable_attributes(_auth_object = nil)
    ['lastname']
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

# This class represents a contact with a first name, last name, and phone number.
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[show edit update destroy]

  # GET /contacts or /contacts.json
  def index
    @q = Contact.ransack(params[:q])
    @contacts = @q.result(distinct: true).order(:lastname).page(params[:page])
  end

  # GET /contacts/1 or /contacts/1.json
  def show; end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit; end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: 'Contact was successfully created.' }
        format.turbo_stream { flash.now[:notice] = 'Contact was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: 'Contact was successfully updated.' }
        format.turbo_stream { flash.now[:notice] = 'Contact was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.turbo_stream { flash.now[:notice] = 'Contact was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def contact_params
    params.fetch(:contact, {}).permit(:firstname, :lastname, :phone)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# The ApplicationHelper module provides helper methods that can be used across the Rails application.
module ApplicationHelper
end

app/helpers/contacts_helper.rb
# frozen_string_literal: true

# The ContactsHelper module provides helper methods specifically related to contacts in the Rails application.
module ContactsHelper
  def full_name(contact)
    "#{contact.firstname} #{contact.lastname}"
  end
end

app/views/contacts/_contact.html.erb
<%= turbo_frame_tag dom_id(contact) do %>
  <%= link_to edit_contact_path(contact), class: 'contact-link', style: 'text-decoration: none;' do %>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <p class="align-middle m-0">
        <strong><%= full_name(contact) %></strong><br>
        <small style="color: grey;"><i class="bi bi-telephone-fill"></i>&nbsp;<%= contact.phone %></small>
      </p>
      <object>
        <%= link_to contact_path(contact), method: :delete, class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } do %>
          <i class="bi bi-trash"></i>
        <% end %>
      </object>
    </li>
  <% end %>
<% end %>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div class="alert alert-danger mt-2" role="alert">
      <h5><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h5>
      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mt-2 mb-2">
    <%= form.label :firstname, class: 'fw-bold' %>
    <%= form.text_field :firstname, class: "form-control" %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :lastname, class: 'fw-bold' %>
    <%= form.text_field :lastname, class: "form-control" %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :phone, class: 'fw-bold' %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div class="d-flex flex-row-reverse">
    <%= form.submit class: "btn btn-primary", style: 'margin-left: 15px;' %>
    <% if contact.id.present? %>
      <%= link_to "Cancel", contact_path(@contact), class: "btn btn-danger" %>
    <% else %>
      <%= link_to "Cancel", contacts_path, class: "btn btn-danger" %>
    <% end %> 
  </div>

<% end %>

app/views/contacts/create.turbo_stream.erb
<%= turbo_stream.prepend "contacts", @contact %>
<%= turbo_stream.update Contact.new, "" %>
<%= turbo_stream.update "contact_notice" do %>
  <%= render "layouts/notice", notice: notice %>
<% end %>

app/views/contacts/destroy.turbo_stream.erb
<%= turbo_stream.update "contact_notice" do %>
  <%= render "layouts/notice", notice: notice %>
<% end %>

app/views/contacts/edit.html.erb
<%= turbo_frame_tag @contact do %>
  <div style="background-color:white;" class="list-group-item justify-content-between align-items-center">
    <%= render "form", contact: @contact %>
  </div>
<% end %>

app/views/contacts/index.html.erb
<div class="container" data-controller="contacts" style="max-width: 700px;">
  <div class="row mb-3">
    <div class="col-6">
      <h2>Contacts</h2>
    </div>
    <div class="col-6">
      <%= link_to "+ Add contact", new_contact_path, class: "btn btn-primary", style: 'float: right;', data: { turbo_frame: dom_id(Contact.new) } %>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-12">
      <%= search_form_for @q, data: { controller: "search-form", search_form_target: "form", turbo_frame: "contacts" } do |f| %>
        <div class="input-group">
          <span class="input-group-text" id="basic-addon1"><i class="bi bi-search"></i></span>
          <%= f.text_field :lastname_cont, class: 'form-control', placeholder: 'Search for contact by last name...', data: { action: "input->search-form#search" } %>
        </div>
      <% end %>
    </div>
  </div>
  <%= turbo_stream_from :contacts %>
  <div class="row justify-content-center">
    <div class="col-12">
      <ul class="list-group">
        <%= turbo_frame_tag "contact_notice" do %>
          <%= render 'layouts/notice', notice: notice %>
        <% end %>
        <%= turbo_frame_tag :contacts do %>
          <%= turbo_frame_tag Contact.new %>
          <% @contacts.each do |contact| %>
            <%= render contact %>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="row mt-3 mb-3">
    <div class="col-12 d-flex justify-content-center">
      <%= paginate @contacts, window: 1 %>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<%= turbo_frame_tag @contact do %>
  <div style="background-color:white;" class="list-group-item justify-content-between align-items-center">
    <%= render "form", contact: @contact %>
  </div>
<% end %>

app/views/contacts/show.html.erb
<%= render @contact %>

app/views/contacts/update.turbo_stream.erb
<%= turbo_stream.replace @contact %>
<%= turbo_stream.update "contact_notice" do %>
  <%= render "layouts/notice", notice: notice %>
<% end %>

app/views/layouts/_notice.html.erb
<% if notice.present? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <div class="row justify-content-center mt-3 mb-3">
        <div class="col-12">
          <h1 style="text-align:center;"><i class="bi bi-person-square"></i>&nbsp;&nbsp;Phone book app</h1>
        </div>
      </div>
    </div>
    <%= yield %>
  </body>
</html>